bootstrap:
  - version: 5.0.0-beta3
    stylesheet: https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css
    javascript: https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.min.js
    javascriptBundle: https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js
    javascriptEsm: https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.esm.min.js
  - version: 5.0.0-beta2
    stylesheet: https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css
    javascript: https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.min.js
    javascriptBundle: https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js
    javascriptEsm: https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.esm.min.js
  - version: 5.0.0-beta1
    stylesheet: https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css
    javascript: https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js
    javascriptBundle: https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js
    javascriptEsm: https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.esm.min.js
  - version: 5.0.0-alpha3
    stylesheet: https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-alpha3/dist/css/bootstrap.min.css
    javascript: https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-alpha3/dist/js/bootstrap.min.js
    javascriptBundle: https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-alpha3/dist/js/bootstrap.bundle.min.js
    javascriptEsm: https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-alpha3/dist/js/bootstrap.esm.min.js
  - version: 5.0.0-alpha2
    stylesheet: https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-alpha2/dist/css/bootstrap.min.css
    javascript: https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-alpha2/dist/js/bootstrap.min.js
    javascriptBundle: https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-alpha2/dist/js/bootstrap.bundle.min.js
    javascriptEsm: https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-alpha2/dist/js/bootstrap.esm.min.js
  - version: 5.0.0-alpha1
    stylesheet: https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-alpha1/dist/css/bootstrap.min.css
    javascript: https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-alpha1/dist/js/bootstrap.min.js
    javascriptBundle: https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-alpha1/dist/js/bootstrap.bundle.min.js
    javascriptEsm: https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-alpha1/dist/js/bootstrap.esm.min.js
  - version: 4.6.0
    stylesheet: https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css
    javascript: https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js
    javascriptBundle: https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js
  - version: 4.5.3
    stylesheet: https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css
    javascript: https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js
    javascriptBundle: https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js
  - version: 4.5.2
    current: true
    stylesheet: https://cdn.jsdelivr.net/npm/bootstrap@4.5.2/dist/css/bootstrap.min.css
    javascript: https://cdn.jsdelivr.net/npm/bootstrap@4.5.2/dist/js/bootstrap.min.js
    javascriptBundle: https://cdn.jsdelivr.net/npm/bootstrap@4.5.2/dist/js/bootstrap.bundle.min.js
  - version: 4.5.1
    stylesheet: https://cdn.jsdelivr.net/npm/bootstrap@4.5.1/dist/css/bootstrap.min.css
    javascript: https://cdn.jsdelivr.net/npm/bootstrap@4.5.1/dist/js/bootstrap.min.js
    javascriptBundle: https://cdn.jsdelivr.net/npm/bootstrap@4.5.1/dist/js/bootstrap.bundle.min.js
  - version: 4.5.0
    stylesheet: https://cdn.jsdelivr.net/npm/bootstrap@4.5.0/dist/css/bootstrap.min.css
    javascript: https://cdn.jsdelivr.net/npm/bootstrap@4.5.0/dist/js/bootstrap.min.js
    javascriptBundle: https://cdn.jsdelivr.net/npm/bootstrap@4.5.0/dist/js/bootstrap.bundle.min.js
  - version: 4.4.1
    stylesheet: https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css
    javascript: https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js
    javascriptBundle: https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.bundle.min.js
  - version: 4.4.0
    stylesheet: https://cdn.jsdelivr.net/npm/bootstrap@4.4.0/dist/css/bootstrap.min.css
    javascript: https://cdn.jsdelivr.net/npm/bootstrap@4.4.0/dist/js/bootstrap.min.js
    javascriptBundle: https://cdn.jsdelivr.net/npm/bootstrap@4.4.0/dist/js/bootstrap.bundle.min.js
  - version: 4.3.1
    stylesheet: https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css
    javascript: https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js
    javascriptBundle: https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.bundle.min.js
  - version: 4.3.0
    stylesheet: https://cdn.jsdelivr.net/npm/bootstrap@4.3.0/dist/css/bootstrap.min.css
    javascript: https://cdn.jsdelivr.net/npm/bootstrap@4.3.0/dist/js/bootstrap.min.js
    javascriptBundle: https://cdn.jsdelivr.net/npm/bootstrap@4.3.0/dist/js/bootstrap.bundle.min.js
  - version: 4.2.1
    stylesheet: https://cdn.jsdelivr.net/npm/bootstrap@4.2.1/dist/css/bootstrap.min.css
    javascript: https://cdn.jsdelivr.net/npm/bootstrap@4.2.1/dist/js/bootstrap.min.js
    javascriptBundle: https://cdn.jsdelivr.net/npm/bootstrap@4.2.1/dist/js/bootstrap.bundle.min.js
  - version: 4.1.3
    stylesheet: https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css
    javascript: https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/js/bootstrap.min.js
    javascriptBundle: https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/js/bootstrap.bundle.min.js
  - version: 4.1.2
    stylesheet: https://cdn.jsdelivr.net/npm/bootstrap@4.1.2/dist/css/bootstrap.min.css
    javascript: https://cdn.jsdelivr.net/npm/bootstrap@4.1.2/dist/js/bootstrap.min.js
    javascriptBundle: https://cdn.jsdelivr.net/npm/bootstrap@4.1.2/dist/js/bootstrap.bundle.min.js
  - version: 4.1.1
    stylesheet: https://cdn.jsdelivr.net/npm/bootstrap@4.1.1/dist/css/bootstrap.min.css
    javascript: https://cdn.jsdelivr.net/npm/bootstrap@4.1.1/dist/js/bootstrap.min.js
    javascriptBundle: https://cdn.jsdelivr.net/npm/bootstrap@4.1.1/dist/js/bootstrap.bundle.min.js
  - version: 4.1.0
    stylesheet: https://cdn.jsdelivr.net/npm/bootstrap@4.1.0/dist/css/bootstrap.min.css
    javascript: https://cdn.jsdelivr.net/npm/bootstrap@4.1.0/dist/js/bootstrap.min.js
    javascriptBundle: https://cdn.jsdelivr.net/npm/bootstrap@4.1.0/dist/js/bootstrap.bundle.min.js
  - version: 4.0.0
    stylesheet: https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css
    javascript: https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js
    javascriptBundle: https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.bundle.min.js
  - version: 4.0.0-beta.3
    stylesheet: https://cdn.jsdelivr.net/npm/bootstrap@4.0.0-beta.3/dist/css/bootstrap.min.css
    javascript: https://cdn.jsdelivr.net/npm/bootstrap@4.0.0-beta.3/dist/js/bootstrap.min.js
    javascriptBundle: https://cdn.jsdelivr.net/npm/bootstrap@4.0.0-beta.3/dist/js/bootstrap.bundle.min.js
  - version: 4.0.0-beta.2
    stylesheet: https://cdn.jsdelivr.net/npm/bootstrap@4.0.0-beta.2/dist/css/bootstrap.min.css
    javascript: https://cdn.jsdelivr.net/npm/bootstrap@4.0.0-beta.2/dist/js/bootstrap.min.js
    javascriptBundle: https://cdn.jsdelivr.net/npm/bootstrap@4.0.0-beta.2/dist/js/bootstrap.bundle.min.js
  - version: 4.0.0-beta
    stylesheet: https://cdn.jsdelivr.net/npm/bootstrap@4.0.0-beta/dist/css/bootstrap.min.css
    javascript: https://cdn.jsdelivr.net/npm/bootstrap@4.0.0-beta/dist/js/bootstrap.min.js
  - version: 4.0.0-alpha.6
    stylesheet: https://cdn.jsdelivr.net/npm/bootstrap@4.0.0-alpha.6/dist/css/bootstrap.min.css
    javascript: https://cdn.jsdelivr.net/npm/bootstrap@4.0.0-alpha.6/dist/js/bootstrap.min.js
  - version: 4.0.0-alpha.5
    stylesheet: https://cdn.jsdelivr.net/npm/bootstrap@4.0.0-alpha.5/dist/css/bootstrap.min.css
    javascript: https://cdn.jsdelivr.net/npm/bootstrap@4.0.0-alpha.5/dist/js/bootstrap.min.js
  - version: 4.0.0-alpha.4
    stylesheet: https://cdn.jsdelivr.net/npm/bootstrap@4.0.0-alpha.4/dist/css/bootstrap.min.css
    javascript: https://cdn.jsdelivr.net/npm/bootstrap@4.0.0-alpha.4/dist/js/bootstrap.min.js
  - version: 4.0.0-alpha.3
    stylesheet: https://cdn.jsdelivr.net/npm/bootstrap@4.0.0-alpha.3/dist/css/bootstrap.min.css
    javascript: https://cdn.jsdelivr.net/npm/bootstrap@4.0.0-alpha.3/dist/js/bootstrap.min.js
  - version: 4.0.0-alpha.2
    stylesheet: https://cdn.jsdelivr.net/npm/bootstrap@4.0.0-alpha.2/dist/css/bootstrap.min.css
    javascript: https://cdn.jsdelivr.net/npm/bootstrap@4.0.0-alpha.2/dist/js/bootstrap.min.js
  - version: 3.4.1
    stylesheet: https://cdn.jsdelivr.net/npm/bootstrap@3.4.1/dist/css/bootstrap.min.css
    javascript: https://cdn.jsdelivr.net/npm/bootstrap@3.4.1/dist/js/bootstrap.min.js
  - version: 3.4.0
    stylesheet: https://cdn.jsdelivr.net/npm/bootstrap@3.4.0/dist/css/bootstrap.min.css
    javascript: https://cdn.jsdelivr.net/npm/bootstrap@3.4.0/dist/js/bootstrap.min.js
  - version: 3.3.7
    stylesheet: https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css
    javascript: https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js
  - version: 3.3.6
    stylesheet: https://cdn.jsdelivr.net/npm/bootstrap@3.3.6/dist/css/bootstrap.min.css
    javascript: https://cdn.jsdelivr.net/npm/bootstrap@3.3.6/dist/js/bootstrap.min.js
  - version: 3.3.5
    stylesheet: https://cdn.jsdelivr.net/npm/bootstrap@3.3.5/dist/css/bootstrap.min.css
    javascript: https://cdn.jsdelivr.net/npm/bootstrap@3.3.5/dist/js/bootstrap.min.js
  - version: 3.3.4
    stylesheet: https://cdn.jsdelivr.net/npm/bootstrap@3.3.4/dist/css/bootstrap.min.css
    javascript: https://cdn.jsdelivr.net/npm/bootstrap@3.3.4/dist/js/bootstrap.min.js
  - version: 3.3.2
    stylesheet: https://cdn.jsdelivr.net/npm/bootstrap@3.3.2/dist/css/bootstrap.min.css
    javascript: https://cdn.jsdelivr.net/npm/bootstrap@3.3.2/dist/js/bootstrap.min.js
  - version: 3.3.1
    stylesheet: https://cdn.jsdelivr.net/npm/bootstrap@3.3.1/dist/css/bootstrap.min.css
    javascript: https://cdn.jsdelivr.net/npm/bootstrap@3.3.1/dist/js/bootstrap.min.js
  - version: 3.3.0
    stylesheet: https://cdn.jsdelivr.net/npm/bootstrap@3.3.0/dist/css/bootstrap.min.css
    javascript: https://cdn.jsdelivr.net/npm/bootstrap@3.3.0/dist/js/bootstrap.min.js
  - version: 3.2.0
    stylesheet: https://cdn.jsdelivr.net/npm/bootstrap@3.2.0/dist/css/bootstrap.min.css
    javascript: https://cdn.jsdelivr.net/npm/bootstrap@3.2.0/dist/js/bootstrap.min.js
  - version: 3.1.1
    stylesheet: https://cdn.jsdelivr.net/npm/bootstrap@3.1.1/dist/css/bootstrap.min.css
    javascript: https://cdn.jsdelivr.net/npm/bootstrap@3.1.1/dist/js/bootstrap.min.js
font-awesome:
  - version: 4.7.0
    current: true
    stylesheet: https://cdn.jsdelivr.net/npm/font-awesome@4.7.0/css/font-awesome.min.css
  - version: 4.6.3
    stylesheet: https://cdn.jsdelivr.net/npm/font-awesome@4.6.3/css/font-awesome.min.css
  - version: 4.6.1
    stylesheet: https://cdn.jsdelivr.net/npm/font-awesome@4.6.1/css/font-awesome.min.css
  - version: 4.5.0
    stylesheet: https://cdn.jsdelivr.net/npm/font-awesome@4.5.0/css/font-awesome.min.css
  - version: 4.4.0
    stylesheet: https://cdn.jsdelivr.net/npm/font-awesome@4.4.0/css/font-awesome.min.css
  - version: 4.3.0
    stylesheet: https://cdn.jsdelivr.net/npm/font-awesome@4.3.0/css/font-awesome.min.css
  - version: 4.2.0
    stylesheet: https://cdn.jsdelivr.net/npm/font-awesome@4.2.0/css/font-awesome.min.css
  - version: 4.1.0
    stylesheet: https://cdn.jsdelivr.net/npm/font-awesome@4.1.0/css/font-awesome.min.css
  - version: 4.0.3
    stylesheet: https://cdn.jsdelivr.net/npm/font-awesome@4.0.3/css/font-awesome.min.css
  - version: 3.2.1
    stylesheet: https://cdn.jsdelivr.net/npm/font-awesome@3.2.1/css/font-awesome.min.css
bootlint:
  - version: 1.1.0
    current: true
    javascript: https://cdn.jsdelivr.net/npm/bootlint@1.1.0/dist/browser/bootlint.min.js
  - version: 1.0.0
    javascript: https://cdn.jsdelivr.net/npm/bootlint@1.0.0/dist/browser/bootlint.min.js
  - version: 0.16.8
    javascript: https://cdn.jsdelivr.net/npm/bootlint@0.16.8/dist/browser/bootlint.min.js
  - version: 0.16.7
    javascript: https://cdn.jsdelivr.net/npm/bootlint@0.16.7/dist/browser/bootlint.min.js
  - version: 0.16.6
    javascript: https://cdn.jsdelivr.net/npm/bootlint@0.16.6/dist/browser/bootlint.min.js
  - version: 0.16.5
    javascript: https://cdn.jsdelivr.net/npm/bootlint@0.16.5/dist/browser/bootlint.min.js
  - version: 0.16.4
    javascript: https://cdn.jsdelivr.net/npm/bootlint@0.16.4/dist/browser/bootlint.min.js
  - version: 0.16.3
    javascript: https://cdn.jsdelivr.net/npm/bootlint@0.16.3/dist/browser/bootlint.min.js
  - version: 0.16.2
    javascript: https://cdn.jsdelivr.net/npm/bootlint@0.16.2/dist/browser/bootlint.min.js
  - version: 0.16.1
    javascript: https://cdn.jsdelivr.net/npm/bootlint@0.16.1/dist/browser/bootlint.min.js
bootswatch3:
  version: 3.4.1
  link: https://bootswatch.com/3/SWATCH_NAME/
  image: https://bootswatch.com/3/SWATCH_NAME/thumbnail.png
  bootstrap: https://cdn.jsdelivr.net/npm/bootswatch@SWATCH_VERSION/SWATCH_NAME/bootstrap.min.css
  themes:
    - name: cerulean
    - name: cosmo
    - name: cyborg
    - name: darkly
    - name: flatly
    - name: journal
    - name: lumen
    - name: sandstone
    - name: simplex
    - name: slate
    - name: spacelab
    - name: superhero
    - name: united
    - name: yeti
bootswatch4:
  version: 4.6.0
  link: https://bootswatch.com/SWATCH_NAME/
  image: https://bootswatch.com/SWATCH_NAME/thumbnail.png
  bootstrap: https://cdn.jsdelivr.net/npm/bootswatch@SWATCH_VERSION/dist/SWATCH_NAME/bootstrap.min.css
  themes:
    - name: cerulean
    - name: cosmo
    - name: cyborg
    - name: darkly
    - name: flatly
    - name: journal
    - name: litera
    - name: lumen
    - name: lux
    - name: materia
    - name: minty
    - name: pulse
    - name: sandstone
    - name: simplex
    - name: sketchy
    - name: slate
    - name: solar
    - name: spacelab
    - name: superhero
    - name: united
    - name: yeti
