font-awesome:
  - version: 4.7.0
    stylesheet: https://cdn.jsdelivr.net/npm/font-awesome@4.7.0/css/font-awesome.min.css
  - version: 4.6.3
    stylesheet: https://cdn.jsdelivr.net/npm/font-awesome@4.6.3/css/font-awesome.min.css
  - version: 4.6.1
    stylesheet: https://cdn.jsdelivr.net/npm/font-awesome@4.6.1/css/font-awesome.min.css
  - version: 4.5.0
    stylesheet: https://cdn.jsdelivr.net/npm/font-awesome@4.5.0/css/font-awesome.min.css
  - version: 4.4.0
    stylesheet: https://cdn.jsdelivr.net/npm/font-awesome@4.4.0/css/font-awesome.min.css
  - version: 4.3.0
    stylesheet: https://cdn.jsdelivr.net/npm/font-awesome@4.3.0/css/font-awesome.min.css
  - version: 4.2.0
    stylesheet: https://cdn.jsdelivr.net/npm/font-awesome@4.2.0/css/font-awesome.min.css
  - version: 4.1.0
    stylesheet: https://cdn.jsdelivr.net/npm/font-awesome@4.1.0/css/font-awesome.min.css
  - version: 4.0.3
    stylesheet: https://cdn.jsdelivr.net/npm/font-awesome@4.0.3/css/font-awesome.min.css
  - version: 3.2.1
    stylesheet: https://cdn.jsdelivr.net/npm/font-awesome@3.2.1/css/font-awesome.min.css
bootlint:
  - version: 1.1.0
    javascript: https://cdn.jsdelivr.net/npm/bootlint@1.1.0/src/bootlint.min.js
  - version: 1.0.0
    javascript: https://cdn.jsdelivr.net/npm/bootlint@1.0.0/src/bootlint.min.js
  - version: 0.16.8
    javascript: https://cdn.jsdelivr.net/npm/bootlint@0.16.8/src/bootlint.min.js
  - version: 0.16.7
    javascript: https://cdn.jsdelivr.net/npm/bootlint@0.16.7/src/bootlint.min.js
  - version: 0.16.6
    javascript: https://cdn.jsdelivr.net/npm/bootlint@0.16.6/src/bootlint.min.js
  - version: 0.16.5
    javascript: https://cdn.jsdelivr.net/npm/bootlint@0.16.5/src/bootlint.min.js
  - version: 0.16.4
    javascript: https://cdn.jsdelivr.net/npm/bootlint@0.16.4/src/bootlint.min.js
  - version: 0.16.3
    javascript: https://cdn.jsdelivr.net/npm/bootlint@0.16.3/src/bootlint.min.js
  - version: 0.16.2
    javascript: https://cdn.jsdelivr.net/npm/bootlint@0.16.2/src/bootlint.min.js
  - version: 0.16.1
    javascript: https://cdn.jsdelivr.net/npm/bootlint@0.16.1/src/bootlint.min.js
  - version: 0.16.0
    javascript: https://cdn.jsdelivr.net/npm/bootlint@0.16.0/src/bootlint.min.js
  - version: 0.15.1
    javascript: https://cdn.jsdelivr.net/npm/bootlint@0.15.1/src/bootlint.min.js
  - version: 0.14.2
    javascript: https://cdn.jsdelivr.net/npm/bootlint@0.14.2/src/bootlint.min.js
  - version: 0.14.1
    javascript: https://cdn.jsdelivr.net/npm/bootlint@0.14.1/src/bootlint.min.js
  - version: 0.14.0
    javascript: https://cdn.jsdelivr.net/npm/bootlint@0.14.0/src/bootlint.min.js
  - version: 0.13.0
    javascript: https://cdn.jsdelivr.net/npm/bootlint@0.13.0/src/bootlint.min.js
  - version: 0.12.0
    javascript: https://cdn.jsdelivr.net/npm/bootlint@0.12.0/src/bootlint.min.js
  - version: 0.11.0
    javascript: https://cdn.jsdelivr.net/npm/bootlint@0.11.0/src/bootlint.min.js
  - version: 0.10.0
    javascript: https://cdn.jsdelivr.net/npm/bootlint@0.10.0/src/bootlint.min.js
  - version: 0.9.2
    javascript: https://cdn.jsdelivr.net/npm/bootlint@0.9.2/src/bootlint.min.js
  - version: 0.9.1
    javascript: https://cdn.jsdelivr.net/npm/bootlint@0.9.1/src/bootlint.min.js
  - version: 0.9.0
    javascript: https://cdn.jsdelivr.net/npm/bootlint@0.9.0/src/bootlint.min.js
  - version: 0.8.0
    javascript: https://cdn.jsdelivr.net/npm/bootlint@0.8.0/src/bootlint.min.js
  - version: 0.7.0
    javascript: https://cdn.jsdelivr.net/npm/bootlint@0.7.0/src/bootlint.min.js
  - version: 0.6.0
    javascript: https://cdn.jsdelivr.net/npm/bootlint@0.6.0/src/bootlint.min.js
  - version: 0.5.0
    javascript: https://cdn.jsdelivr.net/npm/bootlint@0.5.0/src/bootlint.min.js
  - version: 0.4.0
    javascript: https://cdn.jsdelivr.net/npm/bootlint@0.4.0/src/bootlint.min.js
  - version: 0.3.0
    javascript: https://cdn.jsdelivr.net/npm/bootlint@0.3.0/src/bootlint.min.js
  - version: 0.2.0
    javascript: https://cdn.jsdelivr.net/npm/bootlint@0.2.0/src/bootlint.min.js
